version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.3-jessie
    steps:
    - checkout
    - run:
        name: install deps
        command: bundle install
    - run:
        name: Exec fetcher.rb
        command: bundle exec ruby ./scripts/fetcher.rb
    - run:
        name: Exec aggregator
        command: bundle exec ruby ./scripts/aggregator.rb
    - run:
        name: Deploy to github.io
        command: ./deploy-to-gh-pages.sh dist
    #- run: #does not work
    #    name: Deploy update-data to github
    #    command: ./update-data.sh
workflows:
  version: 2
  monthly:
    triggers:
    - schedule:
        cron: "* * 1 * *"
        filters:
          branches:
            only:
            - master
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - gh-pages
  commit:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - gh-pages
