version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.3-jessie
    steps:
    - checkout
    - run:
        name: install deps
        command: bundle install
    - run:
        name: Exec aggregator
        command: bundle exec ruby ./scripts/aggregator.rb
    - run:
        name: Exec fetcher.rb
        command: bundle exec ruby ./scripts/fetcher.rb
    #- run:
     #   name: Deploy update-data to github
      #  command: ./update-data.sh
    - run:
        name: Deploy to github.io
        command: ./deploy-to-gh-pages.sh dist
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - gh-pages
